class Tag(object):
    H4 = 'h4'
    H5 = 'h5'
    H6 = 'h6'
    B = 'b'
    I = 'i'
    QUOTES = 'quotes'
    CODE = 'code'
    LIST = 'list'
    NUM_LIST = 'num_list'
    IMAGE = 'image'
    LINK = 'link'
    LINK_PROFILE = 'link_profile'