class Tag(object):
    B = 'b'
    I = 'i'
    QUOTES = 'quotes'
    LIST = 'list'
    NUM_LIST = 'num_list'
    IMAGE = 'image'
    IMAGE_URL = 'image_url'
    LINK = 'link'
    LINK_PROFILE = 'link_profile'